# Generated by Django 3.2.4 on 2021-06-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recordManager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='recordManager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('recipient_email', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='recordManager.customer')),
            ],
        ),
    ]
